version: '3.1'

services:

  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9091:9091
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: number.devent.kr
      LETSENCRYPT_HOST: number.devent.kr
      LETSENCRYPT_EMAIL: hhj@devent.kr
    network_mode: "bridge"